all:
  children:
    servers:
      hosts:
        whiskey.sparks.codes:
        tango.sparks.codes:
        foxtrot.sparks.codes:
        omega.sparks.codes:
        lambda.sparks.codes:
        echo.sparks.codes:
    servers_with_idracs:
      hosts:
        whiskey.sparks.codes:
        foxtrot.sparks.codes:
        omega.sparks.codes:
        lambda.sparks.codes:
    ios_switches:
      hosts:
        1gbe-switch.sparks.codes:
    nxos_switches:
      hosts:
        10gbe-switch.sparks.codes:
