---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: raphaels-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://raphaelmonrouzeau.github.io/charts/repository/
  timeout: 3m
