---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab-iwrite-software
  namespace: flux-system
spec:
  interval: 15m
  url: https://helm.iwrite.software
  timeout: 3m
