apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - emqx
  - esphome
  - ispy-dvr
  - home-assistant
  # - wyoming-piper
  # - wyoming-whisper
  - zigbee2mqtt
  - zwavejs2mqtt
