---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bambu-studio
  - beaver-habits
  - hajimari
  # - homebox
  - littlelink
  # - mailserver
  # - n8n
  - netboot.xyz
  - ntfy
  - ollama
  - openspeedtest
  - shlink
  # - uptime-kuma
  - vikunja
