---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvr-sparks-codes
  namespace: home
spec:
  selector:
    matchLabels:
      run: nvr-sparks-codes
  replicas: 1
  template:
    metadata:
      labels:
        run: nvr-sparks-codes
    spec:
      containers:
        - name: nvr-sparks-codes
          image: docker.io/doitandbedone/ispyagentdvr
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 1000m
              memory: 4096Mi
          ports:
            - containerPort: 8090
            - containerPort: 3478
              protocol: UDP
            - containerPort: 50000
              protocol: UDP
            - containerPort: 50001
              protocol: UDP
            - containerPort: 50002
              protocol: UDP
            - containerPort: 50003
              protocol: UDP
            - containerPort: 50004
              protocol: UDP
            - containerPort: 50005
              protocol: UDP
            - containerPort: 50006
              protocol: UDP
            - containerPort: 50007
              protocol: UDP
            - containerPort: 50008
              protocol: UDP
            - containerPort: 50009
              protocol: UDP
            - containerPort: 50010
              protocol: UDP
          volumeMounts:
            - name: nvr-sparks-codes-config
              mountPath: "/agent/Media/XML"
            - name: nvr-sparks-codes-media
              mountPath: "/agent/Media/WebServerRoot/Media"
            - name: nvr-sparks-codes-commands
              mountPath: "/agent/Commands"
      volumes:
        - name: nvr-sparks-codes-config
          persistentVolumeClaim:
            claimName: nvr-sparks-codes-config
        - name: nvr-sparks-codes-media
          persistentVolumeClaim:
            claimName: nvr-sparks-codes-media
        - name: nvr-sparks-codes-commands
          persistentVolumeClaim:
            claimName: nvr-sparks-codes-commands

---
apiVersion: v1
kind: Service
metadata:
  name: nvr-sparks-codes-tcp
  namespace: home
  labels:
    run: nvr-sparks-codes
  annotations:
    metallb.universe.tf/allow-shared-ip: nvr-sparks-codes-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.200.5
  ports:
    - name: web-ui
      port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    run: nvr-sparks-codes

---
apiVersion: v1
kind: Service
metadata:
  name: nvr-sparks-codes-udp
  namespace: home
  labels:
    run: nvr-sparks-codes
  annotations:
    metallb.universe.tf/allow-shared-ip: nvr-sparks-codes-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.200.5
  ports:
    - name: turn-server
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: webrtc-0
      port: 50000
      targetPort: 50000
      protocol: UDP
    - name: webrtc-1
      port: 50001
      targetPort: 50001
      protocol: UDP
    - name: webrtc-2
      port: 50002
      targetPort: 50002
      protocol: UDP
    - name: webrtc-3
      port: 50003
      targetPort: 50003
      protocol: UDP
    - name: webrtc-4
      port: 50004
      targetPort: 50004
      protocol: UDP
    - name: webrtc-5
      port: 50005
      targetPort: 50005
      protocol: UDP
    - name: webrtc-6
      port: 50006
      targetPort: 50006
      protocol: UDP
    - name: webrtc-7
      port: 50007
      targetPort: 50007
      protocol: UDP
    - name: webrtc-8
      port: 50008
      targetPort: 50008
      protocol: UDP
    - name: webrtc-9
      port: 50009
      targetPort: 50009
      protocol: UDP
    - name: webrtc-10
      port: 50010
      targetPort: 50010
      protocol: UDP
  selector:
    run: nvr-sparks-codes
