---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k6
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 7.0.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    admin:
      user: sparks
      password: TemporaryPassword2145
    persistence:
      existingClaim: grafana-k6-pvc
      size: 512Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx-external"
      pathType: "Prefix"
      hostname: k6-grafana.sparks.codes
      tls: true
