---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - configmap.yaml
  - pvc-config.yaml
  - pvc-data.yaml
  - pvc-database.yaml
  - external-name.yaml
