apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases
  - games
  - gitlab
  - home
  - kube-system
  - media
  - networking
  - nginx
  - security
  - system-upgrade
  - tools
