---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calibre
  - filebrowser
  # - ghost
  - jellyfin
  - monica
  - photoprism
  - prowlarr
  - qbittorrent
  - sonarr
  # - tubesync
