---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yaml
  - cert-manager.yaml
  - databases.yaml
  - finance.yaml
  - games.yaml
  - gitlab.yaml
  - home.yaml
  - media.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - nginx.yaml
  - rook-ceph.yaml
  - tools.yaml
  - security.yaml
  - system-upgrade.yaml
